# filename: query1.rq
PREFIX book: <http://www.semanticweb.org/tiaquessa/ontologies/2020/10/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.example.com/BookOntology#>

Select ?title ?score ?pageCount
WHERE {
  :Reader1 :wroteRating ?rating .
  ?rating :ratedBook ?book ;
          :rating ?score .
  ?book :title ?title ;
        :pageCount ?pageCount
}