# filename: query3.rq
PREFIX book: <http://www.semanticweb.org/tiaquessa/ontologies/2020/10/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.example.com/BookOntology#>

Select ?content
WHERE {
  :Reader2 :wroteRating/:ratedBook ?book .
  ?book :contains ?content .
}
Group by ?content