# filename: query4.rq
PREFIX : <http://www.semanticweb.org/tiaquessa/ontologies/2020/10/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX book: <http://www.example.com/BookOntology#>

Select ?book ?pages
WHERE {
 ?book rdf:type :ShortStory ;
 book:pageCount ?pages
}
